Granted uri permissions in order to avoid the SecurityException raised when consecutive file sharings were performed:
java.lang.SecurityException: Permission Denial: reading
android.support.v4.content.FileProvider uri content://XXXXX
from pid=XXX, uid=XXXX requires the provider be exported, or
grantUriPermission()